2 lab branch
Sasha-Sobran/javaFirstLab pull request #2
Opened 2023-03-24 14:03 UTC by Sasha-Sobran

2023-03-24 14:27 UTC, MarkoYaminsky requested changes

2023-03-24 14:27 UTC, MarkoYaminsky commented on src/ua/lviv/iot/algo/part1/lab1/Ultrabook.java
> +import lombok.*;
Never use * in imports, this may lead to multiple name collision issues

2023-03-24 14:27 UTC, MarkoYaminsky commented on src/ua/lviv/iot/algo/part1/lab1/DesktopLaptop.java
> +@AllArgsConstructor
For children classes make their own constructor that is able to work with all arguments

2023-03-24 14:27 UTC, MarkoYaminsky commented on src/ua/lviv/iot/algo/part1/lab1/GamingLaptop.java
> +@AllArgsConstructor
For children classes make their own constructor that is able to work with all arguments

2023-03-24 14:27 UTC, MarkoYaminsky commented on src/ua/lviv/iot/algo/part1/lab1/NetBook.java
> +@AllArgsConstructor
For children classes make their own constructor that is able to work with all arguments

2023-03-24 14:27 UTC, MarkoYaminsky commented on src/ua/lviv/iot/algo/part1/lab1/Ultrabook.java
> +@AllArgsConstructor
For children classes make their own constructor that is able to work with all arguments

2023-03-24 18:59 UTC, MarkoYaminsky requested changes

2023-03-24 18:59 UTC, MarkoYaminsky commented on src/ua/lviv/iot/algo/part1/lab1/AbstractLaptopManager.java
> +    }
please do separate logic of invoking Main function and create a separate file for it

2023-03-24 18:59 UTC, MarkoYaminsky commented on src/ua/lviv/iot/algo/part1/lab1/AbstractLaptopManager.java
> +        }
consider adding a method for list iteration and printing

2023-03-24 19:55 UTC, Sasha-Sobran commented on src/ua/lviv/iot/algo/part1/lab1/AbstractLaptopManager.java
> +    }
it`s written in the lab's task

2023-03-24 20:00 UTC, MarkoYaminsky approved these changes

2023-03-28 10:47 UTC, BogdanDidukh2003 requested changes

2023-03-28 10:47 UTC, BogdanDidukh2003 commented on src/ua/lviv/iot/algo/part1/lab2/AbstractLaptopManager.java
> +                collect(Collectors.toList());
```suggestion
        return laptopList.stream()
                .filter(laptop -> laptop.getClass()
                        .getSimpleName()
                        .equals("GamingLaptop"))
                .collect(Collectors.toList());
```

2023-03-28 10:47 UTC, BogdanDidukh2003 commented on src/ua/lviv/iot/algo/part1/lab2/AbstractLaptopManager.java
> +                collect(Collectors.toList());
```suggestion
        return laptopList.stream()
                .filter(laptop -> laptop.getRam() == value)
                .collect(Collectors.toList());
```

2023-03-28 10:47 UTC, BogdanDidukh2003 commented on src/ua/lviv/iot/algo/part1/lab2/AbstractLaptopManager.java
> +    public List<AbstractLaptop> findGamingLaptop() {
```suggestion
    public List<AbstractLaptop> findGamingLaptops() {
```

2023-03-28 10:47 UTC, BogdanDidukh2003 commented on src/ua/lviv/iot/algo/part1/lab2/AbstractLaptopManager.java
> +                        equals("GamingLaptop")).
Extract a constant from this string

2023-03-28 10:47 UTC, BogdanDidukh2003 commented on src/ua/lviv/iot/algo/part1/lab2/AbstractLaptopManager.java
> +                laptops1) {
```suggestion
        for (AbstractLaptop laptop : laptops1) {
```
I guess it's more of an intuitive thing when you should or should not split the line for better readability.  I chop the lines mostly when chain function calls, have lots of parameters, and wrap a line if it is just too long

2023-03-28 10:47 UTC, BogdanDidukh2003 commented on src/ua/lviv/iot/algo/part1/lab2/AbstractLaptopManager.java
> +                laptops2) {
```suggestion
        for (AbstractLaptop laptop : laptops2) {
```

2023-03-28 10:47 UTC, BogdanDidukh2003 commented on src/ua/lviv/iot/algo/part1/lab2/BusinessLaptop.java
> +    public BusinessLaptop(String model, float screenSize, int ram, int storage, int batteryLife, int batteryChargeInPercent, int numberOfPorts, int warrantyInYears) {
Here I would definitely chop the line
```suggestion
    public BusinessLaptop(String model,
        float screenSize,
        int ram,
        int storage, 
        int batteryLife, 
        int batteryChargeInPercent, 
        int numberOfPorts, 
        int warrantyInYears
      ) {
```

2023-03-28 10:47 UTC, BogdanDidukh2003 commented on src/ua/lviv/iot/algo/part1/lab2/GamingLaptop.java
> +    public GamingLaptop(String model, float screenSize, int ram, int storage, int batteryLife, int batteryChargeInPercent, int numberOfFans, String graphicsProcessor) {
And here I would chop

2023-03-28 10:47 UTC, BogdanDidukh2003 commented on src/ua/lviv/iot/algo/part1/lab2/NetBook.java
> +    public NetBook(String model, float screenSize, int ram, int storage, int batteryLife, int batteryChargeInPercent, String operating_system, String WebCam) {
And here I would chop

2023-03-28 10:47 UTC, BogdanDidukh2003 commented on src/ua/lviv/iot/algo/part1/lab2/Ultrabook.java
> +    public Ultrabook(String model, float screenSize, int ram, int storage, int batteryLife, int batteryChargeInPercent, double weight, double thickness) {
Here too

2023-03-30 18:19 UTC, BogdanDidukh2003 approved these changes

2023-03-30 18:50 UTC, MarkoYaminsky approved these changes

2023-04-05 16:05 UTC, merged