added third java lab
Sasha-Sobran/javaFirstLab pull request #3
Opened 2023-04-08 07:41 UTC by Sasha-Sobran

2023-04-08 23:28 UTC, MarkoYaminsky requested changes
Everything's fine, but those 4 fields are redundant

2023-04-08 23:28 UTC, MarkoYaminsky commented on src/test/java/ua/lviv/iot/algo/part1/lab3/AbstractLaptopManagerTest.java
> +    AbstractLaptop laptop4;
Why adding 4 fields which are temporary, needed only to fill laptopsManager and not tested in any way?

2023-04-09 07:44 UTC, MarkoYaminsky approved these changes

2023-04-09 21:53 UTC, BogdanDidukh2003 commented on src/main/java/ua/lviv/iot/algo/part1/lab3/DualLogger.java
> +    public void replaceBatteryInUltrabook(String replaceBatteryInUltrabookException) {
```suggestion
    public void log(String logMessage) {
```

2023-04-09 21:53 UTC, BogdanDidukh2003 commented on src/main/java/ua/lviv/iot/algo/part1/lab3/DualLogger.java
> +    private String ultrabookExceptionMessage;
Your logger should not know anything about what calles it. Remove ultrabook from names here

2023-04-09 21:53 UTC, BogdanDidukh2003 commented on src/main/java/ua/lviv/iot/algo/part1/lab3/GamingLaptop.java
> +    private  Logger logger;
```suggestion
    private Logger logger;
```

2023-04-09 21:53 UTC, BogdanDidukh2003 commented on src/main/java/ua/lviv/iot/algo/part1/lab3/Logger.java
> +    void replaceBatteryInUltrabook(String replaceBatteryInUltrabookException);
Same here

2023-04-09 21:53 UTC, BogdanDidukh2003 commented on src/main/java/ua/lviv/iot/algo/part1/lab3/Netbook.java
> +
```suggestion
```

2023-04-09 21:53 UTC, BogdanDidukh2003 commented on src/main/java/ua/lviv/iot/algo/part1/lab3/Ultrabook.java
> +@Getter
Do you need it?

2023-04-12 17:23 UTC, BogdanDidukh2003 approved these changes

2023-04-12 17:45 UTC, merged